namespace Oblikovati.Contracts.Enums;

public enum DSResultTypeEnum
{
    kPosition1ResultType,
    kVelocity1ResultType,
    kAcceleration1ResultType,
    kDrivingForceUImposed1ResultType,
    kExtentLengthResultType,
    kExtentVelocityResultType,
    kForceResultType,
    kForceXResultType,
    kForceYResultType,
    kForceZResultType,
    kMomentResultType,
    kMomentXResultType,
    kMomentYResultType,
    kMomentZResultType,
    kTraceAccelerationResultType,
    kTraceAccelerationXResultType,
    kTraceAccelerationYResultType,
    kTraceAccelerationZResultType,
    kTracePositionResultType,
    kTracePositionXResultType,
    kTracePositionYResultType,
    kTracePositionZResultType,
    kTraceVelocityResultType,
    kTraceVelocityXResultType,
    kTraceVelocityYResultType,
    kTraceVelocityZResultType,
}