namespace Oblikovati.Domain.Contracts.Enums;

public enum PaperSizeEnum
{
    kPaperSize10x14,
    kPaperSize11x17,
    kPaperSizeA0,
    kPaperSizeA0Oversize,
    kPaperSizeA1,
    kPaperSizeA1Oversize,
    kPaperSizeA2,
    kPaperSizeA2Oversize,
    kPaperSizeA3,
    kPaperSizeA4,
    kPaperSizeA4Small,
    kPaperSizeA5,
    kPaperSizeA6,
    kPaperSizeB0,
    kPaperSizeB1,
    kPaperSizeB2,
    kPaperSizeB3,
    kPaperSizeB4,
    kPaperSizeB5,
    kPaperSizeB6,
    kPaperSizeCSheet,
    kPaperSizeDSheet,
    kPaperSizeESheet,
    kPaperSizeExecutive,
    kPaperSizeFolio,
    kPaperSizeLedger,
    kPaperSizeLegal,
    kPaperSizeLetter,
    kPaperSizeQuarto,
    kPaperSizeCustom,
    kPaperSizeDefault,
}
